allowBuilds:
  core-js: set this to true or false
minimumReleaseAgeExclude:
  - '@react-native/assets-registry@0.86.0'
  - '@react-native/babel-plugin-codegen@0.86.0'
  - '@react-native/babel-preset@0.86.0'
  - '@react-native/codegen@0.86.0'
  - '@react-native/community-cli-plugin@0.86.0'
  - '@react-native/debugger-frontend@0.86.0'
  - '@react-native/debugger-shell@0.86.0'
  - '@react-native/dev-middleware@0.86.0'
  - '@react-native/eslint-config@0.86.0'
  - '@react-native/eslint-plugin@0.86.0'
  - '@react-native/gradle-plugin@0.86.0'
  - '@react-native/js-polyfills@0.86.0'
  - '@react-native/metro-babel-transformer@0.86.0'
  - '@react-native/metro-config@0.86.0'
  - '@react-native/new-app-screen@0.86.0'
  - '@react-native/normalize-colors@0.86.0'
  - '@react-native/typescript-config@0.86.0'
  - '@react-native/virtualized-lists@0.86.0'
  - react-native@0.86.0
